Update operate

diff --git a/operate b/operate
--- a/operate
+++ b/operate
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-
 rc_file=$1
 tag_name=$2
 publickey=$3
@@ -25,7 +24,6 @@ source $rc_file
 
 generate_config(){
     bastionfip=$(openstack server list --name $bastion_server -c Networks -f value | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==2')
-    # haproxyfip=$(openstack server list --name $haproxy_server -c Networks -f value | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==1')
     haproxyfip=$(openstack server show $haproxy_server -c addresses | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==1')
     haproxyfip2=$(openstack server list --name $haproxy_server2 -c Networks -f value | grep -Po '\d+\.\d+\.\d+\.\d+' | awk 'NR==1')
 
@@ -99,21 +97,20 @@ generate_config(){
     echo "ansible_ssh_common_args=' -F $sshconfig '" >> $hostsfile
 }
 
-
 delete_config_and_hostsfile(){
     if [[ -f "$hostsfile" ]] ; then
-    rm "$hostsfile"
+        rm "$hostsfile"
     fi
 
     if [[ -f "$sshconfig" ]] ; then
         rm "$sshconfig"
     fi
-
 }
+
 while true
 do
     reqr_no_of_dev_serv=$(cat servers.conf)
-    echo "$(date) Reading node count from  servers.conf, we need $reqr_no_of_dev_serv dev nodes"
+    echo "$(date) Reading node count from servers.conf, we need $reqr_no_of_dev_serv dev nodes"
 
     exist_serv_previously=$(openstack server list --status ACTIVE --column Name -f value)
     dev_serv_count=$(grep -c $dev_server <<< $exist_serv_previously)
@@ -145,14 +142,23 @@ do
             devserver_name=${dev_server}${sequence}
 
         done
-
+        run_status=1 ## ansible run status if adding servers
     elif (( $reqr_no_of_dev_serv < $dev_serv_count )); then
         no_of_serv_to_remove=$(($dev_serv_count - $reqr_no_of_dev_serv))
         sequence1=0
-        while [[ $sequence1 -lt $no_of_serv_toremove ]]; do
+        while [[ $sequence1 -lt $no_of_serv_to_remove ]]; do
             server_to_delete=$(openstack server list --status ACTIVE -f value -c Name | grep -m1 -oP "${tag_name}"'_dev([1-9]+)')
-            deleted_server=$(openstack server delete "$server_to_delete" --wait)
-            echo "$(date) Deleted server name $server_to_delete "
+            if [[ -n "$server_to_delete" ]]; then
+                deleted_server=$(openstack server delete "$server_to_delete" --wait)
+                if [[ $? -eq 0 ]]; then
+                    echo "$(date) Deleted server name $server_to_delete"
+                    run_status=1 ## ansible run status if deleting servers
+                else
+                    echo "$(date) Failed to delete server name $server_to_delete"
+                fi
+            else
+                echo "$(date) No matching server found for deletion"
+            fi
             ((sequence1++))
         done
     else
